---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spannerdemo{{num}}
  namespace: surbhins
  labels:
    app: spannerdemo{{num}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spannerdemo{{num}}
  template:
    metadata:
      labels:
        app: spannerdemo{{num}}
    spec:
      serviceAccountName: surbhiksa
      containers:
      - name: spannerdemo{{num}}
        image: mrinalsaurabh/surbhispanner:0.1.10
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
          - name: SPANNER_ENABLE_BUILTIN_METRICS
            value: "true"
          - name: DB_NAME_ARG
            value: "--db.projectId=span-cloud-testing"
          - name: PROJECT_ID_ARG
            value: "--db.dbName=projects/span-cloud-testing/instances/surbhi-testing/databases/test-db"
          - name: JAVA_OPTS
            value: "-Dspanner.test-monitoring-endpoint=staging-monitoring.sandbox.googleapis.com:443"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          timeoutSeconds: 5
          periodSeconds: 5
          failureThreshold: 5
          httpGet:
            path: /health/ready
            port: http
        livenessProbe:
          timeoutSeconds: 5
          httpGet:
            path: /health/live
            port: http
          initialDelaySeconds: 50
          periodSeconds: 5
          failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: spannerdemo{{num}}
  namespace: surbhins
spec:
  type: NodePort
  selector:
    app: spannerdemo{{num}}
  ports:
    - protocol: TCP
      port: 600{{num}}
      targetPort: 8080